services:
  - type: web
    name: novaai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn novaai.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: novaai.settings
      - key: SECRET_KEY
        value: "ta_clé_secrète"
      - key: ALLOWED_HOSTS
        value: "render.com"
